name: Build and Deploy

on:
  push:
    branches: [ kavi/development ]
  pull_request:
    branches: [ kavi/development ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}  

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: test-bagspackgo
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .